name: ci

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    env:
      CC: ${{ matrix.compiler }}
      CXX: ${{ matrix.compiler == 'gcc' && 'g++' || 'clang++' }}

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build ccache

      - name: Configure (CMake Preset)
        run: cmake --preset ci-debug

      - name: Build
        run: cmake --build --preset ci-debug -j

      - name: Test
        run: ctest --preset ci-debug --output-on-failure
